---
name: osb-bosh-mongodb

releases:
- name: osb-bosh-mongodb
  version: latest
- name: prometheus
  version: latest
- name: osb-bosh-backup-agent
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 1

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: mongodb
  instances: 3
  azs:
  - z1
  networks:
  - name: service
  vm_type: small
  stemcell: default
  persistent_disk_type: 10GB
  jobs:
  - name: mongodb
    release: osb-bosh-mongodb
    properties:
      mongodb:
        version: 4
        auth:
          admin_users:
          - username: ((root_credentials.username))
            password: ((root_credentials.password))
          - username: ((exporter_credentials.username))
            password: ((exporter_credentials.password))
          backup_users:
          - username: ((backup_credentials.username))
            password: ((backup_credentials.password))
          replica-set:
            keyfile: ((replicaSetKey))
        datadir: /var/vcap/store/mongodb3/
  - name: mongodb_exporter
    release: prometheus
    properties:
      mongodb_exporter:
        mongodb:
          uri: mongodb://((exporter_credentials.username)):((exporter_credentials.password))@127.0.0.1:27017/admin
  - name: backup-agent
    release: osb-bosh-backup-agent
    properties:
      backup_agent:
        username: ((backup_agent_credentials.username))
        password: ((backup_agent_credentials.password))
        scripts_path: /var/vcap/jobs/mongodb/backup

